apiVersion: v1
kind: Service
metadata:
    name: "kubeclub-5406"
    labels:
        app: "kubeclub-5406"
spec:
    type: LoadBalancer
    ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
    selector:
        app: "kubeclub-5406"