apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment-pipeline
  labels:
    app: python-demo-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-demo-cd
  template:
    metadata:
      labels:
        app: python-demo-cd
    spec:
      containers:
      - name: python-demo-cd
        image: actionssheryaarreg.azurecr.io/spark-cd:1
        ports:
        - containerPort: 8001
